title: Cloudlink Docs
description: This site documents the usage of Cloudlink and it's extensions.
theme: just-the-docs

url: https://abichinger.github.io/odoo_cloud_link_docs

aux_links:
  # Docs on Github: https://github.com/abichinger/odoo_cloud_link_docs
  Odoo App Store: https://apps.odoo.com/apps/modules/18.0/cloud_link

callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

content:
  version: "18.0"
  module_name:
    base: Cloudlink - Storage
    gdrive: Cloudlink - Google Drive
    attach: Cloudlink - URL Attachment
    sharepoint: Cloudlink - SharePoint & OneDrive
    sftp: Cloudlink - SFTP (SSH File Transfer Protocol)
    db: Cloudlink - Database
    dropbox: Cloudlink - Dropbox
  technical_name:
    base: cloud_link
    gdrive: cloud_link_gdrive
    attach: cloud_link_attach
    sharepoint: cloud_link_sharepoint
    sftp: cloud_link_sftp
    db: cloud_link_db
    dropbox: cloud_link_dropbox

ga_tracking: G-N51XN1LWNY
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true/nil by default)
