title: Cloudlink Docs
description: This site documents the usage of Cloudlink and it's extensions.
theme: just-the-docs

url: https://abichinger.github.io/odoo_cloud_link_docs/17.0/

aux_links:
  Docs on Github: https://github.com/abichinger/odoo_cloud_link_docs

callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

content:
  version: "17.0"
  module_name:
    base: Cloudlink - Storage
    gdrive: Cloudlink - Google Drive
    attach: Cloudlink - URL Attachment
  technical_name:
    base: cloud_link
    gdrive: cloud_link_gdrive
    attach: cloud_link_attach
